#!/bin/sh
mvn clean package && docker build -t vivekmaniyar/MICROPROFILE_CLIENT_APP .
docker rm -f MICROPROFILE_CLIENT_APP 2>/dev/null || true && docker run -it --name MICROPROFILE_CLIENT_APP -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MICROPROFILE_CLIENT_APP vivekmaniyar/MICROPROFILE_CLIENT_APP
